filter_size: 50
pin_middle: A0
toplist:
- {R: 470, pin_rail: D11, pin_input: A4}
- {R: 21800, pin_rail: A3, pin_input: A2}
#- {R: 1004000, pin_rail: D8, pin_input: A5}
upper_limit: 900
lower_limit: 100
charge_timeout: 15
